domain: postgres
descriptors:
  - key: remote_address
    value: "*"
    rate_limit:
      unit: second
      requests_per_unit: 50

  # Add a separate descriptor for connection establishment
  - key: connection_establishment
    value: "*"
    rate_limit:
      unit: second
      requests_per_unit: 50
